module.exports = Object.freeze({
  USER_NORMAL: 0,
  USER_ADMIN: 1,
  USER_SALE: 2,
  USER_DEACTIVE: 3,
// PRODUCT
  PRODUCT_TRIAL_ID: 1,
  PRODUCT_STANDARD_ID: 2,

// ORDER
  ORDER_STATUS_PENDING: 0,
  ORDER_STATUS_DELIVERING: 1,
  ORDER_STATUS_DONE: 2,
  ORDER_STATUS_CANCEL: 3,

});
